### ISSUE TITLE
Other  conflitcs with wine-mono 

### ISSUE THREAD

**Issue by edpil02** [leonmaxx/wine-proton#2]
You replace wine-proton-mono by wine-mono, but wine-mono needs wine-core  and  wine-common as dependencies.
So got conflicts beetween wine-proton-core and wine-core.
Tried to rebuild wine-mono but  it fails.

**Comment by leonmaxx** [comment]
Thanks for report, going to fix that now.

**Comment by leonmaxx** [comment]
Fixed version building now on COPR, in 30 minutes it will be ready to try.

**Comment by leonmaxx** [comment]
It's done, can You try install now?

**Comment by edpil02** [comment]
Good job  install is perfect now.
Thanks again.

**Comment by leonmaxx** [comment]
Np, closing.
